import { useCallback, useState } from "react";
import { useReactFlow, getNodesBounds, getViewportForBounds } from "@xyflow/react";
import { toPng, toSvg } from "html-to-image";
import { Download, Loader2, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import type { AnalysisResult } from "@/types/repo";

const IMAGE_WIDTH = 4096;
const IMAGE_HEIGHT = 3072;

function downloadDataUrl(dataUrl: string, filename: string) {
  const a = document.createElement("a");
  a.setAttribute("download", filename);
  a.setAttribute("href", dataUrl);
  a.click();
}

interface ExportButtonProps {
  repoName: string;
  analysisResult?: AnalysisResult | null;
}

const ExportButton = ({ repoName, analysisResult }: ExportButtonProps) => {
  const { getNodes } = useReactFlow();
  const [exporting, setExporting] = useState(false);

  const exportImage = useCallback(
    async (format: "png" | "svg") => {
      const el = document.querySelector<HTMLElement>(".react-flow__viewport");
      if (!el) return;

      setExporting(true);
      try {
        const nodes = getNodes();
        const bounds = getNodesBounds(nodes);
        const viewport = getViewportForBounds(bounds, IMAGE_WIDTH, IMAGE_HEIGHT, 0.5, 2, 0.2);

        const fn = format === "png" ? toPng : toSvg;
        const bgColor = getComputedStyle(document.documentElement).getPropertyValue("--background").trim();
        const dataUrl = await fn(el, {
          backgroundColor: bgColor ? `hsl(${bgColor})` : "hsl(240, 20%, 4%)",
          width: IMAGE_WIDTH,
          height: IMAGE_HEIGHT,
          style: {
            width: `${IMAGE_WIDTH}px`,
            height: `${IMAGE_HEIGHT}px`,
            transform: `translate(${viewport.x}px, ${viewport.y}px) scale(${viewport.zoom})`,
          },
        });

        const safeName = repoName.replace(/[^a-zA-Z0-9_-]/g, "_") || "diagram";
        downloadDataUrl(dataUrl, `${safeName}.${format}`);
        toast({ title: `Exported as ${format.toUpperCase()}` });
      } catch (err) {
        console.error("Export failed:", err);
        toast({ title: "Export failed", description: "Could not generate image", variant: "destructive" });
      } finally {
        setExporting(false);
      }
    },
    [getNodes, repoName],
  );

  const exportPdf = useCallback(async () => {
    if (!analysisResult) {
      toast({ title: "No analysis to export", variant: "destructive" });
      return;
    }

    setExporting(true);
    try {
      const el = document.querySelector<HTMLElement>(".react-flow__viewport");
      if (!el) throw new Error("Canvas not found");

      // Dynamically import jspdf and html2canvas
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import("jspdf"),
        import("html2canvas"),
      ]);

      const safeName = repoName.replace(/[^a-zA-Z0-9_-]/g, "_") || "diagram";
      const pdf = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();

      // Page 1: Diagram screenshot
      toast({ title: "Generating PDF...", description: "Capturing diagram (page 1)" });

      const canvas = await html2canvas(el, {
        backgroundColor: "#0a0a12",
        scale: 2,
        useCORS: true,
        logging: false,
      });
      const imgData = canvas.toDataURL("image/png");
      const imgRatio = canvas.width / canvas.height;
      let imgW = pageW - 20;
      let imgH = imgW / imgRatio;
      if (imgH > pageH - 30) {
        imgH = pageH - 30;
        imgW = imgH * imgRatio;
      }

      // Title
      pdf.setFontSize(18);
      pdf.setTextColor(220, 220, 220);
      pdf.text(`${analysisResult.repoName} — Architecture`, 10, 12);
      pdf.setFontSize(8);
      pdf.setTextColor(140, 140, 160);
      pdf.text(`Generated by GitVisualizer AI · ${new Date().toLocaleDateString()}`, 10, 18);

      pdf.addImage(imgData, "PNG", 10, 22, imgW, imgH);

      // Node pages
      const nodes = analysisResult.nodes;
      for (let i = 0; i < nodes.length; i++) {
        const node = nodes[i];
        pdf.addPage();

        // Header
        pdf.setFontSize(14);
        pdf.setTextColor(220, 220, 220);
        pdf.text(node.name, 10, 15);

        pdf.setFontSize(8);
        pdf.setTextColor(100, 180, 220);
        pdf.text(`[${node.type}]  ${node.path}`, 10, 22);

        // Summary
        let y = 32;
        pdf.setFontSize(10);
        pdf.setTextColor(200, 200, 210);
        pdf.text("Summary", 10, y);
        y += 6;
        pdf.setFontSize(8);
        pdf.setTextColor(160, 160, 180);
        const summaryLines = pdf.splitTextToSize(node.summary || "No summary available", pageW - 20);
        pdf.text(summaryLines, 10, y);
        y += summaryLines.length * 4 + 6;

        // Key Functions
        if (node.keyFunctions && node.keyFunctions.length > 0) {
          pdf.setFontSize(10);
          pdf.setTextColor(200, 200, 210);
          pdf.text("Key Functions", 10, y);
          y += 6;
          pdf.setFontSize(8);
          pdf.setTextColor(160, 160, 180);
          for (const fn of node.keyFunctions) {
            pdf.text(`• ${fn}`, 12, y);
            y += 4;
            if (y > pageH - 10) { pdf.addPage(); y = 15; }
          }
          y += 4;
        }

        // Code Snippet
        if (node.codeSnippet) {
          pdf.setFontSize(10);
          pdf.setTextColor(200, 200, 210);
          pdf.text("Code Snippet", 10, y);
          y += 6;
          pdf.setFontSize(7);
          pdf.setTextColor(140, 150, 170);
          const codeLines = pdf.splitTextToSize(node.codeSnippet.slice(0, 2000), pageW - 20);
          for (const line of codeLines) {
            pdf.text(line, 10, y);
            y += 3.5;
            if (y > pageH - 10) { pdf.addPage(); y = 15; }
          }
        }

        // Dependencies
        const incoming = analysisResult.edges.filter((e) => e.target === node.id);
        const outgoing = analysisResult.edges.filter((e) => e.source === node.id);

        if (incoming.length > 0 || outgoing.length > 0) {
          y += 4;
          if (y > pageH - 30) { pdf.addPage(); y = 15; }
          pdf.setFontSize(10);
          pdf.setTextColor(200, 200, 210);
          pdf.text("Dependencies", 10, y);
          y += 6;
          pdf.setFontSize(8);
          pdf.setTextColor(160, 160, 180);

          if (outgoing.length > 0) {
            pdf.text(`Imports (${outgoing.length}):`, 10, y);
            y += 4;
            for (const e of outgoing.slice(0, 10)) {
              const targetNode = nodes.find((n) => n.id === e.target);
              pdf.text(`  → ${targetNode?.name || e.target}${e.label ? ` (${e.label})` : ""}`, 10, y);
              y += 4;
              if (y > pageH - 10) { pdf.addPage(); y = 15; }
            }
          }

          if (incoming.length > 0) {
            y += 2;
            pdf.text(`Imported by (${incoming.length}):`, 10, y);
            y += 4;
            for (const e of incoming.slice(0, 10)) {
              const sourceNode = nodes.find((n) => n.id === e.source);
              pdf.text(`  ← ${sourceNode?.name || e.source}${e.label ? ` (${e.label})` : ""}`, 10, y);
              y += 4;
              if (y > pageH - 10) { pdf.addPage(); y = 15; }
            }
          }
        }

        // Footer
        pdf.setFontSize(6);
        pdf.setTextColor(100, 100, 120);
        pdf.text(`Page ${i + 2} of ${nodes.length + 1}`, pageW - 30, pageH - 5);
      }

      pdf.save(`${safeName}-architecture.pdf`);
      toast({ title: "PDF exported!", description: `${nodes.length + 1} pages generated` });
    } catch (err) {
      console.error("PDF export failed:", err);
      toast({ title: "PDF export failed", variant: "destructive" });
    } finally {
      setExporting(false);
    }
  }, [repoName, analysisResult]);

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" className="h-8 w-8" disabled={exporting}>
          {exporting ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <Download className="h-4 w-4" />
          )}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="min-w-[140px]">
        <DropdownMenuItem onClick={() => exportImage("png")} disabled={exporting}>
          Export PNG
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => exportImage("svg")} disabled={exporting}>
          Export SVG
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportPdf} disabled={exporting} className="gap-2">
          <FileText className="h-3.5 w-3.5" />
          Export PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default ExportButton;
