import { useCallback, useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import type { AnalysisResult } from "@/types/repo";

function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, "_");
}

function nodeShape(name: string, type: string): string {
  const safe = name.replace(/"/g, "'");
  switch (type) {
    case "hook": return `(["${safe}"])`;
    case "component": return `[["${safe}"]]`;
    case "config": return `{"${safe}"}`;
    case "entry": return `(("${safe}"))`;
    case "folder": return `[/"${safe}"/]`;
    default: return `["${safe}"]`;
  }
}

function generateMermaidChart(result: AnalysisResult): string {
  const lines: string[] = ["graph TD"];

  // Group nodes by folder (first path segment)
  const groups = new Map<string, typeof result.nodes>();
  for (const node of result.nodes) {
    const parts = node.path.split("/");
    const group = parts.length > 1 ? parts[0] : "Root";
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group)!.push(node);
  }

  for (const [group, nodes] of groups) {
    if (nodes.length > 1) {
      lines.push(`  subgraph ${sanitizeId(group)}["${group}"]`);
      for (const n of nodes) {
        lines.push(`    ${sanitizeId(n.id)}${nodeShape(n.name, n.type)}`);
      }
      lines.push("  end");
    } else {
      for (const n of nodes) {
        lines.push(`  ${sanitizeId(n.id)}${nodeShape(n.name, n.type)}`);
      }
    }
  }

  for (const edge of result.edges) {
    const label = edge.label || edge.type;
    lines.push(`  ${sanitizeId(edge.source)} -->|${label}| ${sanitizeId(edge.target)}`);
  }

  return lines.join("\n");
}

function generateMarkdown(result: AnalysisResult): string {
  const date = new Date().toLocaleDateString();
  const sections: string[] = [];

  sections.push(`# ${result.repoName} — Architecture\n`);
  sections.push(`> Generated by GitVisualizer AI · ${date}`);
  sections.push(`> ${result.totalFiles ?? result.nodes.length} files analyzed · ${result.nodes.length} modules · ${result.edges.length} connections\n`);

  sections.push("## Architecture Diagram\n");
  sections.push("```mermaid");
  sections.push(generateMermaidChart(result));
  sections.push("```\n");

  sections.push("---\n");
  sections.push("## Modules\n");

  for (const node of result.nodes) {
    sections.push(`### ${node.name}`);
    sections.push(`**Type:** ${node.type} | **Path:** \`${node.path}\`\n`);

    if (node.summary) {
      sections.push(`**Summary:** ${node.summary}\n`);
    }

    if (node.keyFunctions && node.keyFunctions.length > 0) {
      sections.push("**Key Functions:**");
      for (const fn of node.keyFunctions) {
        sections.push(`- \`${fn}\``);
      }
      sections.push("");
    }

    if (node.codeSnippet) {
      sections.push("**Code:**");
      sections.push("```js");
      sections.push(node.codeSnippet.slice(0, 2000));
      sections.push("```\n");
    }

    const outgoing = result.edges.filter((e) => e.source === node.id);
    const incoming = result.edges.filter((e) => e.target === node.id);

    if (outgoing.length > 0 || incoming.length > 0) {
      sections.push("**Dependencies:**");
      if (outgoing.length > 0) {
        const targets = outgoing.map((e) => {
          const t = result.nodes.find((n) => n.id === e.target);
          return t?.name || e.target;
        });
        sections.push(`- **Imports:** ${targets.join(", ")}`);
      }
      if (incoming.length > 0) {
        const sources = incoming.map((e) => {
          const s = result.nodes.find((n) => n.id === e.source);
          return s?.name || e.source;
        });
        sections.push(`- **Imported by:** ${sources.join(", ")}`);
      }
      sections.push("");
    }

    sections.push("---\n");
  }

  return sections.join("\n");
}

interface ExportButtonProps {
  repoName: string;
  analysisResult?: AnalysisResult | null;
}

const ExportButton = ({ repoName, analysisResult }: ExportButtonProps) => {
  const [exporting, setExporting] = useState(false);

  const exportMarkdown = useCallback(() => {
    if (!analysisResult) {
      toast({ title: "No analysis to export", variant: "destructive" });
      return;
    }

    setExporting(true);
    try {
      const md = generateMarkdown(analysisResult);
      const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      const safeName = repoName.replace(/[^a-zA-Z0-9_-]/g, "_") || "diagram";
      a.href = url;
      a.download = `${safeName}-architecture.md`;
      a.click();
      URL.revokeObjectURL(url);
      toast({ title: "Markdown exported!", description: `${analysisResult.nodes.length} modules documented` });
    } catch (err) {
      console.error("Export failed:", err);
      toast({ title: "Export failed", variant: "destructive" });
    } finally {
      setExporting(false);
    }
  }, [repoName, analysisResult]);

  return (
    <Button
      variant="ghost"
      size="icon"
      className="h-8 w-8"
      disabled={exporting || !analysisResult}
      onClick={exportMarkdown}
      title="Download Markdown"
    >
      {exporting ? (
        <Loader2 className="h-4 w-4 animate-spin" />
      ) : (
        <Download className="h-4 w-4" />
      )}
    </Button>
  );
};

export default ExportButton;
